name: Sync API Ref to Production

on:
  workflow_dispatch:
    inputs:
      deploy_tag:
        description: "Input tag version to deploy"
        required: true
        default: ""
  pull_request:
    branches:
      - v3.0
    types:
      - opened
      - closed

jobs:
  DeployProd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      # Sync OpenAPI file to ReadMe
      - name: Upload OpenAPI Spec to ReadMe
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./reference/core.json --key=${{ secrets.README_API_KEY }} --version=3.0

